// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolarMP.Models
{
    public partial class Account
    {
        public Account()
        {
            ConstructionContractCustomer = new HashSet<ConstructionContract>();
            ConstructionContractStaff = new HashSet<ConstructionContract>();
            PaymentProcess = new HashSet<PaymentProcess>();
            Request = new HashSet<Request>();
            Survey = new HashSet<Survey>();
            WarrantyReport = new HashSet<WarrantyReport>();
        }

        [Key]
        [Column("accountId")]
        [StringLength(16)]
        [Unicode(false)]
        public string AccountId { get; set; }
        [Column("username")]
        [StringLength(255)]
        [Unicode(false)]
        public string Username { get; set; }
        [Column("password")]
        [StringLength(255)]
        [Unicode(false)]
        public string Password { get; set; }
        [Column("email")]
        [StringLength(255)]
        [Unicode(false)]
        public string Email { get; set; }
        [Column("firstname")]
        [StringLength(150)]
        public string Firstname { get; set; }
        [Column("lastname")]
        [StringLength(150)]
        public string Lastname { get; set; }
        [Column("phone")]
        [StringLength(15)]
        public string Phone { get; set; }
        [Column("status")]
        public bool Status { get; set; }
        [Column("address")]
        public string Address { get; set; }
        [Required]
        [Column("roleId")]
        [StringLength(10)]
        [Unicode(false)]
        public string RoleId { get; set; }
        [Column("createAt", TypeName = "datetime")]
        public DateTime CreateAt { get; set; }
        [Column("gender")]
        public bool Gender { get; set; }
        [Column("isGoogleProvider")]
        public bool IsGoogleProvider { get; set; }

        [ForeignKey("RoleId")]
        [InverseProperty("Account")]
        public virtual Role Role { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<ConstructionContract> ConstructionContractCustomer { get; set; }
        [InverseProperty("Staff")]
        public virtual ICollection<ConstructionContract> ConstructionContractStaff { get; set; }
        [InverseProperty("Account")]
        public virtual ICollection<PaymentProcess> PaymentProcess { get; set; }
        [InverseProperty("Account")]
        public virtual ICollection<Request> Request { get; set; }
        [InverseProperty("Staff")]
        public virtual ICollection<Survey> Survey { get; set; }
        [InverseProperty("Account")]
        public virtual ICollection<WarrantyReport> WarrantyReport { get; set; }
    }
}