// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolarMP.Models
{
    public partial class Package
    {
        public Package()
        {
            ConstructionContract = new HashSet<ConstructionContract>();
            PackageProduct = new HashSet<PackageProduct>();
            Request = new HashSet<Request>();
        }

        [Key]
        [Column("packageId")]
        [StringLength(16)]
        [Unicode(false)]
        public string PackageId { get; set; }
        [Column("name")]
        [StringLength(255)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("description", TypeName = "text")]
        public string Description { get; set; }
        [Column("price", TypeName = "decimal(10, 2)")]
        public decimal? Price { get; set; }
        [Column("promotionId")]
        [StringLength(16)]
        [Unicode(false)]
        public string PromotionId { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [ForeignKey("PromotionId")]
        [InverseProperty("Package")]
        public virtual Promotion Promotion { get; set; }
        [InverseProperty("Package")]
        public virtual ICollection<ConstructionContract> ConstructionContract { get; set; }
        [InverseProperty("Package")]
        public virtual ICollection<PackageProduct> PackageProduct { get; set; }
        [InverseProperty("Package")]
        public virtual ICollection<Request> Request { get; set; }
    }
}